version: "3.7"
services:

  # to-do database
  to-do-database:
    image: postgres
    container_name: to-do-database
    ports:
      - 5432:5432
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_USER=todouser
      - POSTGRES_PASSWORD=todopassword
      - POSTGRES_DB=todo
    restart: always